version: '3.9'
services:
  server:
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    entrypoint: ['/go/bin/dlv', '--listen=:40000', '--headless=true', '--api-version=2', 'debug', 'cmd/grpc_server/main.go']
    ports:
      - "${DELVE_DEBUG_PORT}:${DELVE_DEBUG_PORT}"